/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerticalsRouteImport } from './routes/verticals'
import { Route as PlanetRouteImport } from './routes/planet'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as CircularRouteImport } from './routes/circular'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsIndexRouteImport } from './routes/verticals.index'
import { Route as VerticalsSlugRouteImport } from './routes/verticals.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VerticalsRoute = VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetRoute = PlanetRouteImport.update({
  id: '/planet',
  path: '/planet',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularRoute = CircularRouteImport.update({
  id: '/circular',
  path: '/circular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsIndexRoute = VerticalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerticalsRoute,
} as any)
const VerticalsSlugRoute = VerticalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VerticalsRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/planet': typeof PlanetRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals/': typeof VerticalsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/planet': typeof PlanetRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals': typeof VerticalsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/planet': typeof PlanetRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals/': typeof VerticalsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/mcp'
    | '/planet'
    | '/verticals'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/verticals/$slug'
    | '/verticals/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/mcp'
    | '/planet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/verticals/$slug'
    | '/verticals'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/mcp'
    | '/planet'
    | '/verticals'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/verticals/$slug'
    | '/verticals/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircularRoute: typeof CircularRoute
  EcosystemRoute: typeof EcosystemRoute
  ImpactRoute: typeof ImpactRoute
  McpRoute: typeof McpRoute
  PlanetRoute: typeof PlanetRoute
  VerticalsRoute: typeof VerticalsRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verticals': {
      id: '/verticals'
      path: '/verticals'
      fullPath: '/verticals'
      preLoaderRoute: typeof VerticalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet': {
      id: '/planet'
      path: '/planet'
      fullPath: '/planet'
      preLoaderRoute: typeof PlanetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circular': {
      id: '/circular'
      path: '/circular'
      fullPath: '/circular'
      preLoaderRoute: typeof CircularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/': {
      id: '/verticals/'
      path: '/'
      fullPath: '/verticals/'
      preLoaderRoute: typeof VerticalsIndexRouteImport
      parentRoute: typeof VerticalsRoute
    }
    '/verticals/$slug': {
      id: '/verticals/$slug'
      path: '/$slug'
      fullPath: '/verticals/$slug'
      preLoaderRoute: typeof VerticalsSlugRouteImport
      parentRoute: typeof VerticalsRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VerticalsRouteChildren {
  VerticalsSlugRoute: typeof VerticalsSlugRoute
  VerticalsIndexRoute: typeof VerticalsIndexRoute
}

const VerticalsRouteChildren: VerticalsRouteChildren = {
  VerticalsSlugRoute: VerticalsSlugRoute,
  VerticalsIndexRoute: VerticalsIndexRoute,
}

const VerticalsRouteWithChildren = VerticalsRoute._addFileChildren(
  VerticalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircularRoute: CircularRoute,
  EcosystemRoute: EcosystemRoute,
  ImpactRoute: ImpactRoute,
  McpRoute: McpRoute,
  PlanetRoute: PlanetRoute,
  VerticalsRoute: VerticalsRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
