/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerticalsRouteImport } from './routes/verticals'
import { Route as PlanetRouteImport } from './routes/planet'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as CircularRouteImport } from './routes/circular'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsSlugRouteImport } from './routes/verticals.$slug'

const VerticalsRoute = VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetRoute = PlanetRouteImport.update({
  id: '/planet',
  path: '/planet',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularRoute = CircularRouteImport.update({
  id: '/circular',
  path: '/circular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsSlugRoute = VerticalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VerticalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/planet': typeof PlanetRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/$slug': typeof VerticalsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/planet': typeof PlanetRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/$slug': typeof VerticalsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/planet': typeof PlanetRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/$slug': typeof VerticalsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/planet'
    | '/verticals'
    | '/verticals/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/planet'
    | '/verticals'
    | '/verticals/$slug'
  id:
    | '__root__'
    | '/'
    | '/circular'
    | '/ecosystem'
    | '/impact'
    | '/planet'
    | '/verticals'
    | '/verticals/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircularRoute: typeof CircularRoute
  EcosystemRoute: typeof EcosystemRoute
  ImpactRoute: typeof ImpactRoute
  PlanetRoute: typeof PlanetRoute
  VerticalsRoute: typeof VerticalsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verticals': {
      id: '/verticals'
      path: '/verticals'
      fullPath: '/verticals'
      preLoaderRoute: typeof VerticalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet': {
      id: '/planet'
      path: '/planet'
      fullPath: '/planet'
      preLoaderRoute: typeof PlanetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circular': {
      id: '/circular'
      path: '/circular'
      fullPath: '/circular'
      preLoaderRoute: typeof CircularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/$slug': {
      id: '/verticals/$slug'
      path: '/$slug'
      fullPath: '/verticals/$slug'
      preLoaderRoute: typeof VerticalsSlugRouteImport
      parentRoute: typeof VerticalsRoute
    }
  }
}

interface VerticalsRouteChildren {
  VerticalsSlugRoute: typeof VerticalsSlugRoute
}

const VerticalsRouteChildren: VerticalsRouteChildren = {
  VerticalsSlugRoute: VerticalsSlugRoute,
}

const VerticalsRouteWithChildren = VerticalsRoute._addFileChildren(
  VerticalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircularRoute: CircularRoute,
  EcosystemRoute: EcosystemRoute,
  ImpactRoute: ImpactRoute,
  PlanetRoute: PlanetRoute,
  VerticalsRoute: VerticalsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
